In [1]:
import numpy as np
import pandas as pd
from scipy.integrate import odeint
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy import optimize
import pickle
import statsmodels.api as sm

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
data = pd.read_csv('LA_County_Covid19_CSA_7day_case_death_table.csv')
demo = pd.read_csv('Census variables.csv')
zips = pd.read_csv('zipneilist.csv')
zips2 = pd.read_csv('usneighborhoods.csv')
zips2 = zips2[zips2['state_id']=='CA']

In [3]:
geomerge = [i for i in data['geo_merge']]
geomerge = list(set(geomerge))
ziploc = [i for i in zips['City/Community']]
ziploc2 = [i for i in zips2['neighborhood']]

In [4]:
zipdict = {}
for i in zips.index:
    zipdict[zips['City/Community'][i]] = zips['Zip Code(s'][i]
zipdict2 = {}
for i in zips2.index:
    zipdict2[zips2['neighborhood'][i]] = zips2['zips'][i]

In [5]:
count1=0
count2=0
longest = 0
damn=[]
zipcodes = {}
for i in geomerge:
    if i!='Los Angeles County':
        count1+=1
        if i not in ziploc:
            if i not in ziploc2:
                print(i)
                sb=i
                count2+=1
            else:
                zipcodes[i] = zipdict2[i].split(' ')
                if len(zipdict2[i].split(' '))>longest:
                    longest =len(zipdict2[i].split(' '))
                    damn = zipdict2[i]
        else:
            zipcodes[i] = zipdict[i].split(',')
            if len(zipdict[i].split(','))>longest:
                longest = len(zipdict[i].split(','))
                damn = zipdict[i]

nan

In [6]:
newzip = np.zeros((len(data),longest))
count= 0
for i in data.index:
    if data['geo_merge'][i] in list(zipcodes.keys()):
        data_zip = zipcodes[data['geo_merge'][i]]
        length = len(data_zip)
        for j in range(length):
            newzip[count,j] = int(data_zip[j])
    count+=1

In [7]:
for i in range(longest):
    globals()['zip%s' % i] =newzip[:,i]
    globals()['zip%s' % i] = pd.Series(globals()['zip%s' % i],index = data.index)
    data[str('zip%s' % i)] =globals()['zip%s' % i]

In [8]:
pickle.dump( data, open( "new_data_with_zip.p", "wb" ) )

In [9]:
data

,Unnamed: 0,ep_date,geo_merge,cases_7day,case_7day_rate,adj_case_7day_rate,case_rate_unstable,death_7day,death_7day_rate,adj_death_7day_rate,...,zip1,zip2,zip3,zip4,zip5,zip6,zip7,zip8,zip9,zip10
0,1,1/16/24,Agoura Hills,11,53.0,50,^,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,1/16/24,Alhambra,38,44.0,38,NaN,0,0,0,...,91803.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,1/16/24,Arcadia,17,29.0,24,^,0,0,0,...,91007.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,1/16/24,Artesia,11,65.0,54,^,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,1/16/24,Avalon,0,0.0,0,NaN,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478941,478942,3/1/20,Whittier,0,0.0,0,NaN,0,0,0,...,90602.0,90603.0,90604.0,90605.0,0.0,0.0,0.0,0.0,0.0,0.0
478942,478943,3/1/20,Whittier Narrows,0,0.0,0,NaN,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
478943,478944,3/1/20,Willowbrook,0,0.0,0,NaN,0,0,0,...,90222.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
478944,478945,3/1/20,Wiseburn,0,0.0,0,NaN,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
478945,478946,3/1/20,NaN,0,0.0,0,NaN,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
data.columns

Index(['Unnamed: 0', 'ep_date', 'geo_merge', 'cases_7day', 'case_7day_rate',
       'adj_case_7day_rate', 'case_rate_unstable', 'death_7day',
       'death_7day_rate', 'adj_death_7day_rate', 'death_rate_unstable',
       'population', 'zip0', 'zip1', 'zip2', 'zip3', 'zip4', 'zip5', 'zip6',
       'zip7', 'zip8', 'zip9', 'zip10'],
      dtype='object')